version: '3.9'
services:

  # ─── Sua aplicação ───────────────────────────────────────
  # ─── PostgresSQL ───────────────────────────────────────
  postgres:
    container_name: toffCo
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=toffco_db'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d toffco_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  # ─── RabbitMQ ───────────────────────────────────────
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5674:5672'
      - '15674:15672'
    networks:
      - app-network

  # ─── Redis ───────────────────────────────────────

  redis:
    image: 'redis:8-alpine'
    container_name: redis-toffco
    ports:
      - '6380:6379'
    restart: unless-stopped
    networks:
      - app-network

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_API_KEY=senha_secreta_23C_ads_Te
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge