spring:
  application:
    name: toffCo
  threads:
    virtual:
      enabled: true
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/toffco_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io #smtp.gmail.com
    port: 587
    username: d2fa3ae3acd9ab #walterro465@gmail.com
    password: 01a5d89028dc2f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      repositories:
        enabled: false

  cache:
    type: redis

jwt:
  secret: ${JWT_SECRET:suaSenha}

server:
  port: 8081

evolution:
  api:
    url: ${EVOLUTION_API_URL:http://localhost:8080}
    instance: ${EVOLUTION_API_INSTANCE:ToffCoBot}
    key: ${EVOLUTION_API_KEY:EVOLUTION_API_KEY}

whatsapp:
  session:
    ttl: ${WHATSAPP_SESSION_TTL:PT24H}

logging:
  level:
    com:
      site:
        toffCo: INFO
