spring:
  application:
    name: toffCo
  threads:
    virtual:
      enabled: true
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/toffco_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5674}
    username: ${RABBITMQ_USER:myuser}
    password: ${RABBITMQ_PASS:secret}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 1000ms
          multiplier: 2
          max-interval: 5000ms
        default-requeue-rejected: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      repositories:
        enabled: false

  cache:
    type: redis

jwt:
  secret: ${JWT_SECRET:chave_secreta_local_ssh}

server:
  port: 8081

evolution:
  api:
    url: ${EVOLUTION_API_URL:http://localhost:8080}
    instance: ${EVOLUTION_API_INSTANCE:Bot_toffBrasil}
    key: ${EVOLUTION_API_KEY:KeyExemplo_teste_naoVali_da}

whatsapp:
  session:
    ttl: ${WHATSAPP_SESSION_TTL:PT24H}

odoo:
  sync:
    enabled: ${ODOO_SYNC_ENABLED:false}

  webhook:
    token: ${ODOO_WEBHOOK_TOKEN:token-webhook-local}

  base-url: ${ODOO_BASE_URL:https://toffbrasil.odoo.com}
  database: ${ODOO_DATABASE:toffbrasil}
  api-key: ${ODOO_API_KEY}

logging:
  level:
    com:
      site:
        toffCo: INFO
    org:
      hibernate:
        sql: DEBUG
        jdbc:
          bind: TRACE


